// <auto-generated />
using System;
using Hrm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hrm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828040329_InitialIam")]
    partial class InitialIam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AccountId", "RoleCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("iam_account_role", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RoleCode = "IAM-ROLE-NV"
                        },
                        new
                        {
                            AccountId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RoleCode = "IAM-ROLE-HR"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.IdentityAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailCty")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdpSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IdpSubject")
                        .IsUnique();

                    b.ToTable("iam_identity_account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            DisplayName = "Dev IAM",
                            EmailCty = "dev@company.local",
                            EmployeeCode = "MNV-DEV",
                            IdpSubject = "local-dev",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.Role", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RoleCode");

                    b.ToTable("iam_role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleCode = "IAM-ROLE-NV",
                            Name = "Nhân viên"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-LM",
                            Name = "Line Manager"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-HR",
                            Name = "HR / C&B"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-IT",
                            Name = "IT Admin"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-PGD",
                            Name = "PGD / BGĐ"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.AccountRole", b =>
                {
                    b.HasOne("Hrm.Domain.Identity.Entities.IdentityAccount", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hrm.Domain.Identity.Entities.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.IdentityAccount", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
