// <auto-generated />
using System;
using Hrm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hrm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904022352_AddLifSliceCNPlus3Locks")]
    partial class AddLifSliceCNPlus3Locks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.EducationLevel", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Code");

                    b.ToTable("emp_education_level", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "EDU-THPT",
                            Name = "Trung học phổ thông",
                            Status = "Active"
                        },
                        new
                        {
                            Code = "EDU-CD",
                            Name = "Cao đẳng",
                            Status = "Active"
                        },
                        new
                        {
                            Code = "EDU-DH",
                            Name = "Đại học",
                            Status = "Active"
                        },
                        new
                        {
                            Code = "EDU-INACTIVE",
                            Name = "Ngừng hiệu lực (test)",
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.EmpAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorIdpSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("emp_audit_log", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cccd")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EducationLevelCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EmailCty")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("LineManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrgUnitCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("SeniorityStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Cccd")
                        .IsUnique();

                    b.HasIndex("EducationLevelCode");

                    b.HasIndex("EmailCty")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("OrgUnitCode");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("emp_employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            EmailCty = "dev@company.local",
                            EmployeeCode = "MNV-DEV",
                            FullName = "Dev IAM",
                            LineManagerEmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            OrgUnitCode = "ORG-HQ",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            EmailCty = "handover@company.local",
                            EmployeeCode = "MNV-HO",
                            FullName = "Handover NV",
                            OrgUnitCode = "ORG-HQ",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.EmployeeContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsProbation")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("emp_contract", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.LineManagerChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProposedLineManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedByIdpSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Status");

                    b.ToTable("emp_line_manager_change", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.OrgUnit", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Code");

                    b.ToTable("emp_org_unit", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "ORG-HQ",
                            Name = "Trụ sở HN",
                            Status = "Active"
                        },
                        new
                        {
                            Code = "ORG-INACTIVE",
                            Name = "Đơn vị ngừng",
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.SeniorityRule", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BasisType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Code");

                    b.ToTable("emp_seniority_rule", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "SR-DEFAULT",
                            BasisType = "ContractStartDate",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AccountId", "RoleCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("iam_account_role", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RoleCode = "IAM-ROLE-NV"
                        },
                        new
                        {
                            AccountId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RoleCode = "IAM-ROLE-HR"
                        },
                        new
                        {
                            AccountId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            RoleCode = "IAM-ROLE-IT"
                        },
                        new
                        {
                            AccountId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleCode = "IAM-ROLE-NV"
                        },
                        new
                        {
                            AccountId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleCode = "IAM-ROLE-LM"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.IdentityAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailCty")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdpSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IdpSubject")
                        .IsUnique();

                    b.ToTable("iam_identity_account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            DisplayName = "Dev IAM",
                            EmailCty = "dev@company.local",
                            EmployeeCode = "MNV-DEV",
                            IdpSubject = "local-dev",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            DisplayName = "IT Dev",
                            EmailCty = "it@company.local",
                            IdpSubject = "it-dev",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DisplayName = "Handover NV (LM)",
                            EmailCty = "handover@company.local",
                            EmployeeCode = "MNV-HO",
                            IdpSubject = "local-lm",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.Role", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RoleCode");

                    b.ToTable("iam_role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleCode = "IAM-ROLE-NV",
                            Name = "Nhân viên"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-LM",
                            Name = "Line Manager"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-HR",
                            Name = "HR / C&B"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-IT",
                            Name = "IT Admin"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-PGD",
                            Name = "PGD / BGĐ"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Leave.Entities.LeaveBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EntitledDays")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<decimal>("UsedDays")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year")
                        .IsUnique();

                    b.ToTable("lev_leave_balance", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            EmployeeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            EntitledDays = 12m,
                            UsedDays = 0m,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Leave.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("C1ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("C1ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("C1ReviewedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("C2ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("C2ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("C2ReviewedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DayPart")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HandoverEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("boolean");

                    b.Property<string>("LeaveTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalDays")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeCode");

                    b.ToTable("lev_leave_request", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Leave.Entities.LeaveType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("DeductsAnnualBalance")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Code");

                    b.ToTable("lev_leave_type", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "LEV-ANNUAL",
                            DeductsAnnualBalance = true,
                            Name = "Phép năm",
                            Status = "Active"
                        },
                        new
                        {
                            Code = "LEV-UNPAID",
                            DeductsAnnualBalance = false,
                            Name = "Phép không hưởng lương",
                            Status = "Active"
                        },
                        new
                        {
                            Code = "LEV-SICK",
                            DeductsAnnualBalance = false,
                            Name = "Phép ốm/BHXH",
                            Status = "Active"
                        },
                        new
                        {
                            Code = "LEV-MARRIAGE",
                            DeductsAnnualBalance = false,
                            Name = "Phép kết hôn",
                            Status = "Active"
                        },
                        new
                        {
                            Code = "LEV-BEREAVEMENT",
                            DeductsAnnualBalance = false,
                            Name = "Phép tang chế",
                            Status = "Active"
                        },
                        new
                        {
                            Code = "LEV-MATERNITY",
                            DeductsAnnualBalance = false,
                            Name = "Nghỉ chế độ Nam/Nữ",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Lifecycle.Entities.LifAccessLockOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CrReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIdpSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEarlySecurityCr")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetSystems")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate");

                    b.HasIndex("CaseId");

                    b.ToTable("lif_access_lock_outbox", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Lifecycle.Entities.LifOffChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMust")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("lif_off_checklist_item", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1e1e1e1-e1e1-e1e1-e1e1-e1e1e1e1e1e1"),
                            Code = "OFF-RETURN-LAPTOP",
                            IsActive = true,
                            IsMust = true,
                            Name = "Thu hồi laptop / thiết bị",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("e2e2e2e2-e2e2-e2e2-e2e2-e2e2e2e2e2e2"),
                            Code = "OFF-RETURN-BADGE",
                            IsActive = true,
                            IsMust = true,
                            Name = "Thu hồi thẻ ra vào",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("e3e3e3e3-e3e3-e3e3-e3e3-e3e3e3e3e3e3"),
                            Code = "OFF-HANDOVER",
                            IsActive = true,
                            IsMust = true,
                            Name = "Bàn giao công việc / tài liệu",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("e4e4e4e4-e4e4-e4e4-e4e4-e4e4e4e4e4e4"),
                            Code = "OFF-EXIT-INTERVIEW",
                            IsActive = true,
                            IsMust = false,
                            Name = "Phỏng vấn nghỉ việc",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Lifecycle.Entities.LifOffChecklistTick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CheckedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OffboardingCaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OffboardingCaseId", "ItemCode")
                        .IsUnique();

                    b.ToTable("lif_off_checklist_tick", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Lifecycle.Entities.LifOffboardingCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIdpSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CrmSpLockedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EarlyCrReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GitLockedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEarlySecurityCr")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastWorkingDayN")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LockAsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("LockedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("ResignationSignedDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Status");

                    b.ToTable("lif_offboarding_case", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayAllowanceCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("pay_allowance_catalog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3"),
                            Code = "PC-ANTRUA",
                            IsActive = true,
                            Name = "Phụ cấp ăn trưa"
                        },
                        new
                        {
                            Id = new Guid("c4c4c4c4-c4c4-c4c4-c4c4-c4c4c4c4c4c4"),
                            Code = "PC-XANG",
                            IsActive = true,
                            Name = "Phụ cấp xăng xe"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayContractAllowance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Code")
                        .IsUnique();

                    b.ToTable("pay_contract_allowance", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5c5c5c5-c5c5-c5c5-c5c5-c5c5c5c5c5c5"),
                            Amount = 730000m,
                            Code = "PC-ANTRUA",
                            EmployeeCode = "MNV-DEV",
                            EmployeeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayContractSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("pay_contract_salary", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8c8c8c8-c8c8-c8c8-c8c8-c8c8c8c8c8c8"),
                            Amount = 10000000m,
                            EmployeeCode = "MNV-DEV",
                            EmployeeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayExportOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CcAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIdpSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PdfFileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PeriodYm")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodYm");

                    b.ToTable("pay_export_outbox", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BhAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BhRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("ContractAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LeaveDaysPaid")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("LeaveDaysUnpaid")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("MonthlyAllowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("NTinh")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("NetPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Ot15")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Ot20")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Ot30")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TimeWageFactor")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("TncnAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TncnRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("WorkDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("pay_line", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayMonthlyAllowance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PeriodYm")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodYm", "EmployeeId", "Code")
                        .IsUnique();

                    b.ToTable("pay_monthly_allowance", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PeriodYm")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime?>("RanAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RanByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodYm")
                        .IsUnique();

                    b.ToTable("pay_period", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayRegulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("DecimalValue")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("pay_regulation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1c1c1c1-c1c1-c1c1-c1c1-c1c1c1c1c1c1"),
                            Code = "PROBATION_TIME_WAGE_FACTOR",
                            DecimalValue = 0.85m,
                            Name = "Hệ số lương thời gian thử việc"
                        },
                        new
                        {
                            Id = new Guid("c2c2c2c2-c2c2-c2c2-c2c2-c2c2c2c2c2c2"),
                            Code = "STANDARD_WORK_DAYS_DEFAULT",
                            DecimalValue = 22m,
                            Name = "Ngày công chuẩn mặc định (khi tháng chưa có lịch)"
                        },
                        new
                        {
                            Id = new Guid("c6c6c6c6-c6c6-c6c6-c6c6-c6c6c6c6c6c6"),
                            Code = "BH_EMPLOYEE_RATE",
                            DecimalValue = 0.10m,
                            Name = "Tỷ lệ BH người lao động (hiệu lực kỳ)"
                        },
                        new
                        {
                            Id = new Guid("c7c7c7c7-c7c7-c7c7-c7c7-c7c7c7c7c7c7"),
                            Code = "TNCN_TEMP_RATE",
                            DecimalValue = 0.05m,
                            Name = "Tỷ lệ TNCN tạm (hiệu lực kỳ)"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayWorkdayCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PeriodYm")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<decimal>("StandardWorkDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodYm")
                        .IsUnique();

                    b.ToTable("pay_workday_calendar", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Probation.Entities.ProbationCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("prb_criterion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4"),
                            Code = "CRIT-WORK",
                            IsActive = true,
                            Name = "Kết quả công việc",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("d5d5d5d5-d5d5-d5d5-d5d5-d5d5d5d5d5d5"),
                            Code = "CRIT-ATTITUDE",
                            IsActive = true,
                            Name = "Thái độ / kỷ luật",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Probation.Entities.ProbationEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CriteriaPayloadJson")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DecidedOutcomeCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExtendDurationCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("ProbationEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ProposedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProposedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProposedNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ProposedOutcomeCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode");

                    b.HasIndex("EmployeeId", "Status");

                    b.ToTable("prb_evaluation", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Probation.Entities.ProbationExtendDuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Months")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("prb_extend_duration", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6d6d6d6-d6d6-d6d6-d6d6-d6d6d6d6d6d6"),
                            Code = "EXT-1M",
                            IsActive = true,
                            Months = 1,
                            Name = "Gia hạn 1 tháng",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("d7d7d7d7-d7d7-d7d7-d7d7-d7d7d7d7d7d7"),
                            Code = "EXT-2M",
                            IsActive = true,
                            Months = 2,
                            Name = "Gia hạn 2 tháng",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Probation.Entities.ProbationOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("prb_outcome", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1d1d1d1-d1d1-d1d1-d1d1-d1d1d1d1d1d1"),
                            Code = "PASS",
                            IsActive = true,
                            Name = "Đạt",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("d2d2d2d2-d2d2-d2d2-d2d2-d2d2d2d2d2d2"),
                            Code = "EXTEND",
                            IsActive = true,
                            Name = "Gia hạn",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("d3d3d3d3-d3d3-d3d3-d3d3-d3d3d3d3d3d3"),
                            Code = "FAIL",
                            IsActive = true,
                            Name = "Không đạt",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Probation.Entities.ProbationReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("AssigneeEmployeeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("AssigneeEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIdpSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("InAppMessage")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateOnly>("ProbationEndDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AsOfDate");

                    b.HasIndex("EmployeeId", "Kind", "ProbationEndDate")
                        .IsUnique();

                    b.ToTable("prb_reminder", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("HasMustErrors")
                        .HasColumnType("boolean");

                    b.Property<string>("PeriodYm")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TemplateVersionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedByIdpSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodYm");

                    b.ToTable("tim_import_batch", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsOk")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Ot15")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("Ot20")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("Ot30")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("OtUnclassified")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WorkDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "RowNumber")
                        .IsUnique();

                    b.ToTable("tim_import_row", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LeaveDaysOther")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("LeaveDaysPaid")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("LeaveDaysUnpaid")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Ot15")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Ot20")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Ot30")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("OtUnclassified")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WorkDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("tim_timesheet_line", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CommittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommittedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PeriodYm")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<Guid?>("SourceImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodYm")
                        .IsUnique();

                    b.ToTable("tim_period", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetTemplateColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColumnKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("MapsTo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateVersionId", "ColumnKey")
                        .IsUnique();

                    b.ToTable("tim_template_column", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1"),
                            ColumnKey = "mnv",
                            DisplayName = "Mã NV",
                            IsRequired = true,
                            MapsTo = "EmployeeCode",
                            SortOrder = 1,
                            TemplateVersionId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1")
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            ColumnKey = "n_thuc",
                            DisplayName = "Ngày công thực",
                            IsRequired = true,
                            MapsTo = "WorkDays",
                            SortOrder = 2,
                            TemplateVersionId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1")
                        },
                        new
                        {
                            Id = new Guid("b3b3b3b3-b3b3-b3b3-b3b3-b3b3b3b3b3b3"),
                            ColumnKey = "ot_15",
                            DisplayName = "OT 1.5",
                            IsRequired = false,
                            MapsTo = "Ot15",
                            SortOrder = 3,
                            TemplateVersionId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1")
                        },
                        new
                        {
                            Id = new Guid("b4b4b4b4-b4b4-b4b4-b4b4-b4b4b4b4b4b4"),
                            ColumnKey = "ot_20",
                            DisplayName = "OT 2.0",
                            IsRequired = false,
                            MapsTo = "Ot20",
                            SortOrder = 4,
                            TemplateVersionId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1")
                        },
                        new
                        {
                            Id = new Guid("b5b5b5b5-b5b5-b5b5-b5b5-b5b5b5b5b5b5"),
                            ColumnKey = "ot_30",
                            DisplayName = "OT 3.0",
                            IsRequired = false,
                            MapsTo = "Ot30",
                            SortOrder = 5,
                            TemplateVersionId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1")
                        },
                        new
                        {
                            Id = new Guid("b6b6b6b6-b6b6-b6b6-b6b6-b6b6b6b6b6b6"),
                            ColumnKey = "ot_unclassified",
                            DisplayName = "OT chưa phân loại",
                            IsRequired = false,
                            MapsTo = "OtUnclassified",
                            SortOrder = 6,
                            TemplateVersionId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1")
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VersionCode")
                        .IsUnique();

                    b.ToTable("tim_template_version", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            Name = "Mẫu công V1 (seed)",
                            PublishedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublishedByIdpSubject = "seed",
                            Status = "Active",
                            VersionCode = "TIM-V1"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.Employee", b =>
                {
                    b.HasOne("Hrm.Domain.Employees.Entities.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hrm.Domain.Employees.Entities.OrgUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EducationLevel");

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.EmployeeContract", b =>
                {
                    b.HasOne("Hrm.Domain.Employees.Entities.Employee", "Employee")
                        .WithOne("Contract")
                        .HasForeignKey("Hrm.Domain.Employees.Entities.EmployeeContract", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.LineManagerChangeRequest", b =>
                {
                    b.HasOne("Hrm.Domain.Employees.Entities.Employee", "Employee")
                        .WithMany("LineManagerChangeRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.AccountRole", b =>
                {
                    b.HasOne("Hrm.Domain.Identity.Entities.IdentityAccount", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hrm.Domain.Identity.Entities.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Hrm.Domain.Leave.Entities.LeaveRequest", b =>
                {
                    b.HasOne("Hrm.Domain.Leave.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayLine", b =>
                {
                    b.HasOne("Hrm.Domain.Payroll.Entities.PayPeriod", "Period")
                        .WithMany("Lines")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetImportRow", b =>
                {
                    b.HasOne("Hrm.Domain.Timekeeping.Entities.TimesheetImportBatch", "Batch")
                        .WithMany("Rows")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetLine", b =>
                {
                    b.HasOne("Hrm.Domain.Timekeeping.Entities.TimesheetPeriod", "Period")
                        .WithMany("Lines")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetTemplateColumn", b =>
                {
                    b.HasOne("Hrm.Domain.Timekeeping.Entities.TimesheetTemplateVersion", "TemplateVersion")
                        .WithMany("Columns")
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateVersion");
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.Employee", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("LineManagerChangeRequests");
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.IdentityAccount", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("Hrm.Domain.Payroll.Entities.PayPeriod", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetImportBatch", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetPeriod", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Hrm.Domain.Timekeeping.Entities.TimesheetTemplateVersion", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
