// <auto-generated />
using System;
using Hrm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hrm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cccd")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EmailCty")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("LineManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrgUnitCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Cccd")
                        .IsUnique();

                    b.HasIndex("EmailCty")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("OrgUnitCode");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("emp_employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            EmailCty = "dev@company.local",
                            EmployeeCode = "MNV-DEV",
                            FullName = "Dev IAM",
                            OrgUnitCode = "ORG-HQ",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.EmployeeContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsProbation")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("emp_contract", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.LineManagerChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProposedLineManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedByIdpSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedByIdpSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Status");

                    b.ToTable("emp_line_manager_change", (string)null);
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.OrgUnit", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Code");

                    b.ToTable("emp_org_unit", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "ORG-HQ",
                            Name = "Trụ sở HN",
                            Status = "Active"
                        },
                        new
                        {
                            Code = "ORG-INACTIVE",
                            Name = "Đơn vị ngừng",
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AccountId", "RoleCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("iam_account_role", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RoleCode = "IAM-ROLE-NV"
                        },
                        new
                        {
                            AccountId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RoleCode = "IAM-ROLE-HR"
                        },
                        new
                        {
                            AccountId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            RoleCode = "IAM-ROLE-IT"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.IdentityAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailCty")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdpSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IdpSubject")
                        .IsUnique();

                    b.ToTable("iam_identity_account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            DisplayName = "Dev IAM",
                            EmailCty = "dev@company.local",
                            EmployeeCode = "MNV-DEV",
                            IdpSubject = "local-dev",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            DisplayName = "IT Dev",
                            EmailCty = "it@company.local",
                            IdpSubject = "it-dev",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.Role", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RoleCode");

                    b.ToTable("iam_role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleCode = "IAM-ROLE-NV",
                            Name = "Nhân viên"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-LM",
                            Name = "Line Manager"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-HR",
                            Name = "HR / C&B"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-IT",
                            Name = "IT Admin"
                        },
                        new
                        {
                            RoleCode = "IAM-ROLE-PGD",
                            Name = "PGD / BGĐ"
                        });
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.Employee", b =>
                {
                    b.HasOne("Hrm.Domain.Employees.Entities.OrgUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.EmployeeContract", b =>
                {
                    b.HasOne("Hrm.Domain.Employees.Entities.Employee", "Employee")
                        .WithOne("Contract")
                        .HasForeignKey("Hrm.Domain.Employees.Entities.EmployeeContract", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.LineManagerChangeRequest", b =>
                {
                    b.HasOne("Hrm.Domain.Employees.Entities.Employee", "Employee")
                        .WithMany("LineManagerChangeRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.AccountRole", b =>
                {
                    b.HasOne("Hrm.Domain.Identity.Entities.IdentityAccount", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hrm.Domain.Identity.Entities.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Hrm.Domain.Employees.Entities.Employee", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("LineManagerChangeRequests");
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.IdentityAccount", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("Hrm.Domain.Identity.Entities.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
